### ISSUE TITLE
Request for cell identities by barcode

### ISSUE THREAD

**Issue by dyammons** [BradRosenbergLab/equinepbmc#3]
Hi, 
I am hoping to apply your annotated dataset to assist in classification of an equine scrna dataset and was wondering if you could provide your annotations by cell barcode (meta data from the Seurat object) in a `.csv` file.

Thank you,
Dylan

**Comment by roosheelpatel** [comment]
Hi Dylan,

happy to help. Can you please provide a valid email address and I can send the file along later today.

roosheel

**Comment by dyammons** [comment]
Hi Roosheel,
You can send it to dylan.ammons@colostate.edu

Thanks!
-Dylan
